### ISSUE TITLE
请问patch是怎么生成的？

### ISSUE THREAD

**Issue by tsao-chi** [Mohist-Community/MohistRemapGuide#1]
https://github.com/Mohist-Community/Mohist/tree/1.15.2/patches
https://github.com/Mohist-Community/Mohist/tree/1.12.2/patches

是按照README的方法得到`remap-***.jar`然后反编译并`diff`吗？

**Comment by Mgazul** [comment]
对 参照nms-patches中的补丁文件，再参照和srg表和remap-***.jar
